### ISSUE TITLE
Broken link in FC legend

### ISSUE THREAD

**Issue by alexgleith** [digitalearthafrica/config#28]
https://github.com/digitalearthafrica/config/blob/3b04fcebbef130c501a63f973128c3c64a1f6596/services/ows.py#L2928

**Comment by SuperKogito** [comment]
I think broken links are a common issue and a radical solution to this problem is automatically checking and reporting them. Luckily the new GitHub actions and  workflows help with that. I recently wrote an action that just does that. [URLs-checker](https://github.com/marketplace/actions/urls-checker) will check and report broken links, which is useful to spot similar issues to this one.

**Comment by tom-butler** [comment]
@alexgleith Looks like it's moved to here: https://data.dea.ga.gov.au/fractional-cover/FC_legend.png

**Comment by tom-butler** [comment]
It should probably be moved to the digitalearthafrica bucket though

**Comment by alexgleith** [comment]
Yeah, it is, but the broken link is FC percentiles. On thinking about it I realise that we don't have percentiles for FC in Africa, so that link is the right one!

I'll copy the file to a DE Africa bucket and fix the link.
